/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExamplesImport } from './routes/examples'
import { Route as IndexImport } from './routes/index'
import { Route as DocsPageIdImport } from './routes/docs.$pageId'

// Create/Update Routes

const ExamplesRoute = ExamplesImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsPageIdRoute = DocsPageIdImport.update({
  id: '/docs/$pageId',
  path: '/docs/$pageId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesImport
      parentRoute: typeof rootRoute
    }
    '/docs/$pageId': {
      id: '/docs/$pageId'
      path: '/docs/$pageId'
      fullPath: '/docs/$pageId'
      preLoaderRoute: typeof DocsPageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/docs/$pageId': typeof DocsPageIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/docs/$pageId': typeof DocsPageIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/docs/$pageId': typeof DocsPageIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examples' | '/docs/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples' | '/docs/$pageId'
  id: '__root__' | '/' | '/examples' | '/docs/$pageId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesRoute: typeof ExamplesRoute
  DocsPageIdRoute: typeof DocsPageIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesRoute: ExamplesRoute,
  DocsPageIdRoute: DocsPageIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/examples",
        "/docs/$pageId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/examples": {
      "filePath": "examples.tsx"
    },
    "/docs/$pageId": {
      "filePath": "docs.$pageId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
